In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('Book2.csv')
x=df.iloc[:, :-1].values
y=df.iloc[:, -1].values

In [3]:
print(x)

[[  8  41 126  73]
 [ 71  72  69  74]
 [ 34  72  61  99]
 ...
 [ 13  61 104  77]
 [  5  21 144  77]
 [ 56  83  70  95]]


In [4]:
print(y)

[26 28 15 39 32 26 33 35 14 17 19 12 20 13 21 13 35 29 21 13 19 18 17 12
 21 16 16 28 27 12 13 36 19 35 29 12 20 22 24 12 14 19 20 29 17 16 21 18
 13 21 18 22 25 34 31 14 14 15 22 18 33 24 18 36 15 33 24 24 12 26 20 13
 15 26 18 14 19 15 18 35 23 13 19 19 36 21 33 21 13 30 31 13 33 17 12 26
 14 29 19 14 19 19 29 14 19 35 13 39 28 19 17 37 33 30 13 19 32 31 17 18
 24 29 15 14 34 21 13 16 12 14 39 16 21 18 32 25 15 31 12 15 17 17 26 17
 33 21 14 20 18 19 29 16 16 12 25 13 16 13 34 16 32 15 27 19 12 37 21 14
 15 22 18 12 14 36 15 14 15 18 27 19 31 28 15 13 15 27 36 12 12 31 20 13
 13 16 34 28 19 20 31 13 38 12 33 37 14 12 28 17 14 19 13 30 38 28 13 37
 24 31 16 18 18 16 17 21 36 29 20 13 19 17 18 13 14 15 33 26 18 18 34 24
 17 35 18 14 29 25 19 14 38 22 39 23 15 16 13 22 16 29 14 14 24 19 38 16
 15 19 21 26 31 18 15 14 31 14 27 33 13 13 30 25 12 18 13 38 15 20 37 25
 29 33 23 21 12 14 30 31 30 13 33 15 18 18 18 36 20 25 24 26 16 36 30 24
 27 17 17 20 31 35 12 34 15 28 35 22 18 26 19 15 37

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [6]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=1000,random_state=0)
regressor.fit(x_train,y_train)

RandomForestRegressor(n_estimators=1000, random_state=0)

In [7]:
y_pred=regressor.predict(x_test)

In [8]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.6360051056426921

In [9]:
import pickle
pickle_out=open('RR.pkl','wb')
pickle.dump(regressor,pickle_out)
pickle_out.close()